name: Clojure CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    env:
      MAVEN_REPO_AWS_ACCESS_KEY_ID: ${{ secrets.MAVEN_REPO_AWS_ACCESS_KEY_ID }}
      MAVEN_REPO_AWS_ACCESS_KEY_SECRET: ${{ secrets.MAVEN_REPO_AWS_ACCESS_KEY_SECRET }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Run tests
      run: lein test
